authors:
  keith:
    name: Keith Hayden
    description: Digital Novelist & Technologist. HAC Studios.
    url: https://keithhayden.net
    avatar: https://storage.ghost.io/c/18/bf/18bf29db-1cec-4857-a9dc-e2e94a86d2bf/content/images/2025/08/Keith-Hayden---Headshot-Square-Jan-2025--Author-Nation--1.jpg
